version: '3'

services:
  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./back
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - db  # Dépend du service MongoDB

  flask:
    build: ./Machine_Learning
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - db  # Dépend du service MongoDB

  front:
    build: ./front
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo-data:
